### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by flashdrive1** [ariel-waisman/LabelsToROIs#3]
When I try to load the plugin, I get the error message SyntaxError: ("mismatched input ',' expecting COLON", ('<string>', 309, 73, "                       with open(full_table_path, 'a') as full_table_file, open(path_to_multiple_Tables, 'r') as current_table:\n")). I saw other people were having this same issue and to update their version of ImageJ. I went to the Help->update ImageJ and it says I am running the most recent version yet am still having the same error message. Thanks

**Comment by ariel-waisman** [comment]
Hi! Sorry to hear you had issues running the plugin. This plugin was built for use in FIJI, which is a version of ImageJ full of libraries and tools for biological-image analysis. Are you using ImageJ or FIJI? I got the same error when trying to run the plugin with basic imageJ.  I will try to see what's wrong and fix it. But you shouldn't have any problems using it in Fiji.

Download link: https://imagej.net/software/fiji/

Hope that helps!
Nice weekend, 
Ariel

**Comment by flashdrive1** [comment]
Thanks. I was using basic ImageJ, with FIJI it works.
