### ISSUE TITLE
exclude cells on edges

### ISSUE THREAD

**Issue by JustineJiao** [ariel-waisman/LabelsToROIs#8]
Hi there,

When I process polygonal cells and calculate their cell area, I want to exclude the cells on edges, like this image:

![CT4-1-1 1-1](https://user-images.githubusercontent.com/58281975/168710595-212d78bb-2ab8-4f02-a4e6-f55199e1ed52.png)
 
Because these cell margins are tightly linked, so I can not exclude the outlines on edges by dilate, which will affect cell size.

Is there any idea to solve this issue?

Thanks a lot!

Justine Jiao at hzau.edu

**Comment by ariel-waisman** [comment]
Hi Justine Jiao, 
The current version of LabelsToRois does not include the option of removing the border labels before conversion into ROIs. However, there is a simple way to solve this. Starting from your label image, you can use the MorpholibJ plugin that comes with FIJI, go to Label Images / Remove Border Labels and remove all the labels from the Top, Bottom, Left and Right borders. You can then use this new label image to load it into LabelsToROIs. 

Hope this solved this problem! 
Good luck!
Ariel

![Border Labels](https://user-images.githubusercontent.com/20975344/169171762-9b11e298-def1-4427-b0ae-b669bb17f454.png)

**Comment by JustineJiao** [comment]
It works! Thank you very much!
Justine
